export const contactStyles = {
  section: "py-24 px-4 bg-background dark:bg-zinc-950",
  container: "max-w-6xl mx-auto",
  grid: "grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16",
  heading: "display-font text-4xl sm:text-5xl font-bold text-foreground dark:text-white mb-4 tracking-tight",
  intro: "text-muted-foreground dark:text-zinc-400 mb-8 leading-relaxed",
  linkList: "space-y-4",
  linkItem:
    "flex items-start gap-4 p-4 rounded-2xl bg-muted dark:bg-zinc-900 border border-border dark:border-zinc-800 hover:border-border dark:hover:border-zinc-700 transition-all duration-300",
  linkIconWrap: "p-2.5 rounded-lg bg-card dark:bg-zinc-800 mt-0.5",
  linkIcon: "w-5 h-5 text-emerald-600 dark:text-emerald-500",
  linkContent: "flex-1 min-w-0",
  linkLabel: "font-semibold text-foreground dark:text-white",
  linkValue: "text-sm text-muted-foreground dark:text-zinc-400 truncate",
  formWrap: "group",
  formCardContent: "p-8",
  formTitle: "display-font text-2xl sm:text-3xl font-bold text-foreground dark:text-white mb-6",
  form: "space-y-6",
  nameEmailGrid: "grid grid-cols-1 sm:grid-cols-2 gap-4",
  fieldLabel: "block text-sm font-medium text-muted-foreground dark:text-zinc-400 mb-2",
  fieldError: "mt-1 text-xs text-red-500",
  submitErrorWrap: "p-4 rounded-lg bg-red-500/10 border border-red-500/30",
  submitErrorText: "text-sm font-medium text-red-600 dark:text-red-400",
  submitSuccessWrap: "p-4 rounded-lg bg-emerald-500/10 border border-emerald-500/30",
  submitSuccessText: "text-sm font-medium text-emerald-600 dark:text-emerald-400",
  submitIcon: "mr-2 w-4 h-4",
} as const
