export const experienceStyles = {
  section: "py-24 px-4 bg-background dark:bg-zinc-950",
  container: "max-w-6xl mx-auto",
  emptyState: "p-8 rounded-lg bg-muted dark:bg-zinc-900 border border-border dark:border-zinc-800 text-center",
  emptyText: "text-muted-foreground dark:text-zinc-400",
  list: "space-y-4",
  item: "group",
  content: "p-6",
  header: "flex flex-col md:flex-row md:items-start md:justify-between gap-4 mb-4",
  headerLeft: "flex-1",
  roleRow: "flex items-center gap-3 mb-2",
  iconWrap: "p-2 rounded-lg bg-card dark:bg-zinc-800 group-hover:bg-emerald-600/20",
  icon: "w-4 h-4 text-muted-foreground dark:text-zinc-400 group-hover:text-emerald-500 transition-colors duration-300",
  role: "text-lg font-semibold text-foreground dark:text-white",
  company: "text-sm text-muted-foreground dark:text-zinc-400 font-medium",
  description: "text-muted-foreground dark:text-zinc-400 mb-4 text-sm leading-relaxed",
  skills: "flex flex-wrap gap-2 mb-4",
  meta: "flex flex-col sm:flex-row sm:items-center gap-2 pt-4 border-t border-border dark:border-zinc-800 text-xs text-muted-foreground dark:text-zinc-500",
  metaItem: "flex items-center gap-1.5",
  divider: "hidden sm:block text-border dark:text-zinc-700",
  metaIcon: "w-3.5 h-3.5",
} as const
