export const homeStyles = {
  section: "relative py-24 px-4 bg-background dark:bg-zinc-950 overflow-hidden",
  backdrop: "absolute inset-0 bg-gradient-to-b from-zinc-900 via-zinc-950/90 to-zinc-950 pointer-events-none",
  container: "relative z-10 max-w-6xl mx-auto",
  grid: "grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center",
  content: "text-left",
  introBlock: "mb-6",
  headingPrefix: "text-muted-foreground dark:text-zinc-400 text-lg mb-2",
  name: "display-font text-5xl sm:text-6xl lg:text-7xl font-bold tracking-tight text-foreground dark:text-white",
  description: "text-muted-foreground dark:text-zinc-400 max-w-xl mb-8 leading-relaxed",
  socials: "flex gap-3",
  socialButton:
    "w-11 h-11 rounded-full border-border dark:border-zinc-800 hover:border-emerald-500 hover:text-emerald-500 transition-all duration-300",
  socialIcon: "w-5 h-5 text-foreground dark:text-zinc-300",
  imageWrap: "relative flex justify-center items-center",
  imageBounds: "relative w-72 h-80 sm:w-80 sm:h-80 lg:w-96 lg:h-96",
  imageBaseGlow: "absolute inset-0 rounded-full bg-gradient-to-br from-zinc-900 to-zinc-950 dark:from-zinc-900 dark:to-black opacity-60",
  imageOuterGlow: "absolute -inset-8 rounded-full bg-zinc-800/20 dark:bg-zinc-800/30 blur-2xl",
  imageFrame: "relative w-full h-full rounded-full overflow-hidden border-2 border-border dark:border-zinc-800 shadow-2xl shadow-black/30",
  image: "w-full h-full object-cover",
  badgeWrap: "absolute -bottom-6 left-1/2 -translate-x-1/2 whitespace-nowrap",
  badge: "inline-flex items-center gap-2 px-4 py-2 rounded-full bg-card dark:bg-zinc-900 border border-border dark:border-zinc-800",
  badgeDot: "w-2 h-2 rounded-full bg-emerald-500",
  badgeText: "text-xs font-medium text-muted-foreground dark:text-zinc-400",
} as const
